### ISSUE TITLE
Untraslated Credits

### ISSUE THREAD

**Issue by rafael-57** [ooa113y/umineko-catbox-english#15]
Platform: [Yuzu]
Issue type: [untranslated video]
Episode number: [1]
Chapter name: [Tea Party subtitles]
Screenshot of issue: [attach one if relevant]

I just noticed that subtitles aren't translated (I've only read ep1 tea party for now), is there any plan to translate them? 

Beatrice, Battler etc. are all written in Kanji. Would it be possible to translate the subtitles using resources from Umineko Project?

Thanks

**Comment by ooa113y** [comment]
I have no idea what "subtitles" you are talking about, to be honest.
Do you mean the credits section, the large scrolling image at the very end? If so, my reason here is basically this: 1) this image is not story-relevant, 2) the list of people involved with the project has grown and using the old credits from the Alchemist release would no longer be accurate, 3) since the list is longer, it also scrolls a little slower, which would mean using the old list would result in the scroll finishing too early, before the song does, which would be quite weird.

And... 4) I don't really feel like spending several hours re-typing the gigantic list of credits with all the new names involved (not to mention, I'm probably going to romanize them wrong since my Japanese knowledge is virtually non-existent) and trying to fit it into an image.

**Comment by rafael-57** [comment]
Sorry I typed subtitles when I was thinking of the credits. 

Yeah it's exactly those. I understand it's not simple at all then

**Comment by ooa113y** [comment]
Right, thanks for confirming. I might get to these at some point, but honestly these are extremely low priority.

**Comment by ooa113y** [comment]
(I have decided I'm not going to bother with this 😅)
